### PR TITLE
added a notebook with an analysis of asymptotic memory overheads

### PR DESCRIPTION
**Pull request by nbronson**

### CODE REVIEW

**Comment by nbronson** [comment]
Based on the talk, it seems like flat_hash_set will have

    "rehash": [(16.0/14, 0, 16.0/14)],
    "insert": [],

which means that all dynamically-sized data and metadata is in a single allocation, and just before rehash it occupies (16/14*sizeof(value_type) + 16/14)*size() bytes. That will make it about 2% more memory efficient than F14ValueSet.

**Comment by fowles** [comment]
It's actually slightly more complicated because we switched to using floating windows instead of fixed offset windows.   (16/14*sizeof(value_type) + 16/14)*size() + 16

**Comment by fowles** [comment]
I have had a busy couple days but will try this out and pull it in tomorrow

**Comment by fowles** [comment]
This is really great!  Thanks.

**Pull request merged**
